<a href="https://colab.research.google.com/github/yaretziaguilar/THC/blob/main/19Octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr= np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#dimensiones
a= np.array(42)
b= np.array([1,2,3,4,5])
c= np.array([[1,2,3],[4,5,6]])
d= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
arr= np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("segundo elmento de la primer fila:", arr[0,1])

segundo elmento de la primer fila: 2


In [59]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
vari=arr[0]+arr[1]+arr[2]
print(vari[0]+vari[1]+vari[2])

45


In [51]:
A=[[1,2,3],[4,5,6],[7,8,9]]
suma=0
for i in range(len(A)):
  for j in range(len(A)):
    suma+=A[i][j]
print(suma)

45


In [68]:
A=([1,2,3],[4,5,6],[7,8,9])
B=([5,8,2],[5,9,6],[4,7,1])
def producto_esc(A,B):
 for i in range(len(A)):
    C+=A[i]* B[i]
 return(C)
a=producto_esc(A,B)
print(a)

UnboundLocalError: ignored

In [71]:
A=([1,2,3],[4,5,6],[7,8,9])
B=([5,8,2],[5,9,6],[4,7,1])
def ProdPunto(a, b):
#para listas, producto punto
  PP=0.0
  for i in range(len(a)):
    PP=PP+a[i]*b[i]
    return PP

In [72]:
arr2=np.array([[1,2,3],[4,5,6],[1,1,1]])
arr3=np.array([[1,8,5],[4,9,6],[4,1,7]])
Pp_por_reng=np.array([0,0,0])
Pp_por_col=np.array([0,0,0])

In [75]:
for i in range(len(arr2)):
  Pp_por_reng[i]=ProdPunto(arr2[i],arr3[i])
Pp_por_reng

array([ 1, 16,  4])

In [77]:
def AgarraCol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.append(a[i,col])
  return np.array(nuevo)

In [78]:
col1=AgarraCol(arr2,0)
col1

array([1, 4, 1])

In [79]:
for i in range(len(arr2)):
 Pp_por_col[i]=ProdPunto(AgarraCol(arr2,i),AgarraCol(arr3,i))
Pp_por_col

array([ 1, 16, 15])