<a href="https://colab.research.google.com/github/yaretziaguilar/THC/blob/main/24Octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])

[2 4]


In [5]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [6]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [9]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:])

[ 6  7  8  9 10]


In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:3,2])

[3 8]


In [11]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,2])

[3]


In [12]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,3])

[4 9]


In [13]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,4])

5


In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [17]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,2:6])

[[3 4 5]]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8])
x= np.searchsorter(arr,7)
print(x)

AttributeError: ignored

In [20]:
arr=np.array([41,42,43,44])
filter_arr=arr> 42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [21]:
arr=np.array([41,42,43,44])
filter_arr=arr%2==0
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]


In [23]:
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
print(suma)

[5 7 9]


In [27]:
resta=x-y
print(resta)

[-3 -3 -3]


In [28]:
prod=x*y
print(f"La multiplicación es {prod}")

La multiplicación es [ 4 10 18]


In [29]:
div=x/y
print(f"la división es {div}")

la división es [0.25 0.4  0.5 ]


In [30]:
print(f"número pi= {np.pi}")

número pi= 3.141592653589793


In [33]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
coseno=np.cos(angulos)
print(f"Los senos{seno}")
print(f"De los ángulos {angulos}")
print(f"Los cosenos {coseno}")

Los senos[0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los ángulos [0.         1.57079633 3.14159265]
Los cosenos [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [34]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


In [35]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
matriz=x.reshape(4,2)
matriz

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
x.reshape(-1,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [39]:
x.reshape(-1,1).shape

(8, 1)

In [40]:
x=np.linspace(0,1,3)
x

array([0. , 0.5, 1. ])

In [42]:
x=np.linspace(0,1,4)
x

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [44]:
np.random.uniform(0,1,6)

array([0.3722586 , 0.80673464, 0.99161792, 0.01169283, 0.23274021,
       0.28665708])

In [50]:
np.random.randint(0,10,size=1)

array([7])

In [ ]:

int(input("Colocar un nunmero alertarorio del 1 al 10 "))
c=np.random.randint(0,11,size=1)
print("Es este tu numero?",c )
input("¿si o no?")


Colocar un nunmero alertarorio del 1 al 10 9
Es este tu numero? [6]
